### ISSUE TITLE
Fail to copy

### ISSUE THREAD

**Issue by packeterrors** [trustedsec/tscopy#12]
I've downloaded the latest build shown as of last month for TScopy_x64.exe

I'm on Windows 2010 x64
Microsoft Windows [Version 10.0.19044.1526]

I wrote a small batch to try to back up my profile to another drive. The program worked well to copy specific hive files but I received the error below when running the batch and only a handful of files and folders were copied. I disabled Windows Defender real-time protection just in case. No change.

:: BATCH
@Echo Off
C:\Backup\Admin\batch\TScopy_x64.exe -r -o "H:\BACKUP" -f c:\users\pc\*
pause

Output from running the program

2022-02-13 20:36:19,851 - tscopy - INFO - Copying c:\users\pc\ntuser.dat{53b39e88-18c4-11ea-a811-000d3aa4692b}.tmcontainer00000000000000000002.regtrans-ms to H:\BACKUP\users\pc\ntuser.dat{53b39e88-18c4-11ea-a811-000d3aa4692b}.tmcontainer00000000000000000002.regtrans-ms
2022-02-13 20:36:19,867 - tscopy - INFO - Copying c:\users\pc\.shadow to H:\BACKUP\users\pc\.shadow
2022-02-13 20:36:20,332 - tscopy - INFO - Copying c:\users\pc\.vscode to H:\BACKUP\users\pc\.vscode
2022-02-13 20:38:36,638 - tscopy - INFO - Copying c:\users\pc\advanced_port_scanner_comments.bin to H:\BACKUP\users\pc\advanced_port_scanner_comments.bin
2022-02-13 20:38:36,654 - tscopy - INFO - Copying c:\users\pc\downloads to H:\BACKUP\users\pc\downloads
2022-02-13 20:38:36,661 - tscopy - INFO - Copying c:\users\pc\recent to H:\BACKUP\users\pc\recent
2022-02-13 20:38:36,668 - tscopy - INFO - Copying c:\users\pc\saved games to H:\BACKUP\users\pc\saved games
2022-02-13 20:38:36,678 - tscopy - INFO - Copying c:\users\pc\ntuser.dat to H:\BACKUP\users\pc\ntuser.dat
2022-02-13 20:38:36,733 - tscopy - INFO - Copying c:\users\pc\intel to H:\BACKUP\users\pc\intel
2022-02-13 20:38:36,789 - tscopy - INFO - Copying c:\users\pc\.idlerc to H:\BACKUP\users\pc\.idlerc
2022-02-13 20:38:36,799 - tscopy - INFO - Copying c:\users\pc\cisco packet tracer 8.1.0 to H:\BACKUP\users\pc\cisco packet tracer 8.1.0
2022-02-13 20:38:36,838 - tscopy - INFO - Copying c:\users\pc\cookies to H:\BACKUP\users\pc\cookies
2022-02-13 20:38:36,845 - tscopy - INFO - Copying c:\users\pc\advanced_port_scanner_aliases.bin to H:\BACKUP\users\pc\advanced_port_scanner_aliases.bin
2022-02-13 20:38:36,858 - tscopy - INFO - Copying c:\users\pc\tracing to H:\BACKUP\users\pc\tracing
2022-02-13 20:38:36,871 - tscopy - INFO - Copying c:\users\pc\onedrive to H:\BACKUP\users\pc\onedrive
2022-02-13 20:38:36,880 - tscopy - ERROR - Traceback (most recent call last):
  File "C:\Users\tsir\Desktop\sandbox\tscopy-2021-08-31\TScopy\tscopy.py", line 492, in __copyfile
  File "C:\Users\tsir\Desktop\sandbox\tscopy-2021-08-31\TScopy\tscopy.py", line 371, in __copydir
  File "C:\Users\tsir\Desktop\sandbox\tscopy-2021-08-31\TScopy\tscopy.py", line 395, in __copydirfiles
  File "C:\Users\tsir\Desktop\sandbox\tscopy-2021-08-31\TScopy\tscopy.py", line 542, in __getChildIndex
AttributeError: 'Attribute' object has no attribute 'value'

2022-02-13 20:38:36,884 - tscopy - INFO - Job Took 137.84100008010864 seconds
Press any key to continue . . .

**Comment by snus-b** [comment]
Packeterrors, Thanks for reporting. Can you rerun with the "--debug" flag for more verbose output. If you are comfortable could you share the "mft.pickle" file as it contains all the meta data about the NTFS that has been parsed by TScopy.

Thanks
